import { type Activity } from '@/types/timeline';

const activitys: Activity[] = [
  {
    name: '幻兽聚',
    title: '趣夏唯渝',
    dateStart: new Date('2024-07-12 UTC+8'),
    dateEnd: new Date('2024-07-14 UTC+8'),
    city: '重庆',
    address: '万垚酒店',
  },
  {
    name: '云幽岛',
    title: '盛夏探幽记',
    dateStart: new Date('2024-07-19 UTC+8'),
    dateEnd: new Date('2024-07-21 UTC+8'),
    province: '四川',
    city: '成都',
    address: '温江皇冠假日酒店',
  },
  {
    name: 'Hi Furry',
    title: '糖果奇遇',
    dateStart: new Date('2024-10-01 UTC+8'),
    dateEnd: new Date('2024-10-04 UTC+8'),
    province: '广东',
    city: '佛山',
    address: '佛山希尔顿酒店',
  },
  {
    name: '云幽岛',
    title: '云幽涂月节',
    dateStart: new Date('2025-01-17 UTC+8'),
    dateEnd: new Date('2025-01-19 UTC+8'),
    province: '四川',
    city: '成都',
    address: '温江皇冠假日酒店',
  },
  {
    name: '万兽汇',
    title: '八方来客',
    dateStart: new Date('2025-03-14 UTC+8'),
    dateEnd: new Date('2025-03-16 UTC+8'),
    province: '浙江',
    city: '杭州',
    address: '萧山国际机场凯悦酒店',
  },
  {
    name: 'Hi Furry',
    title: '古域织影',
    dateStart: new Date('2025-05-01 UTC+8'),
    dateEnd: new Date('2025-05-04 UTC+8'),
    province: '广东',
    city: '佛山',
    address: '佛山希尔顿酒店',
  },
  {
    name: '幻兽聚',
    title: '星幽疑讯',
    dateStart: new Date('2025-07-18 UTC+8'),
    dateEnd: new Date('2025-07-20 UTC+8'),
    province: '湖南',
    city: '长沙',
    address: '步步高朋福喜来登酒店',
  },
  {
    name: '落茜聚',
    title: '次科山探险',
    dateStart: new Date('2025-07-25 UTC+8'),
    dateEnd: new Date('2025-07-27 UTC+8'),
    province: '四川',
    city: '成都',
    address: '成都友豪锦江酒店',
  },
  {
    name: '云幽岛',
    title: '寅虎逐夏记',
    dateStart: new Date('2025-08-08 UTC+8'),
    dateEnd: new Date('2025-08-10 UTC+8'),
    city: '重庆',
    address: '融创施柏阁酒店',
  },
  {
    name: 'Hi Furry',
    title: '森野纪事',
    dateStart: new Date('2025-10-01 UTC+8'),
    dateEnd: new Date('2025-10-04 UTC+8'),
    province: '广东',
    city: '广州',
    address: '南沙岭南东方酒店×国际金融论坛会议中心',
  },
  {
    name: '福瑞星球',
    title: '星越秋收',
    dateStart: new Date('2025-10-04 UTC+8'),
    dateEnd: new Date('2025-10-06 UTC+8'),
    province: '四川',
    city: '成都',
    address: '成都龙之梦大酒店',
  },
  {
    name: '三无行兽',
    title: '第一届',
    dateStart: new Date('2025-11-21 UTC+8'),
    dateEnd: new Date('2025-11-23 UTC+8'),
    city: '重庆',
    address: '万垚酒店',
  },
  {
    name: '云幽岛',
    title: '云幽端月节',
    dateStart: new Date('2026-01-30 UTC+8'),
    dateEnd: new Date('2026-02-01 UTC+8'),
    province: '四川',
    city: '成都',
    address: '成都雅居乐豪生大酒店',
  },
];
export default activitys;
